
// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file was generated by plugin-generate-structured-data.
// To update, modify the source markdown files or the plugin configuration and re-run the generator.

import React from 'react';
import { useLocation } from '@docusaurus/router';

export default function Root({ children }) {
  const location = useLocation();

  const baseUrl = "https://horizonrepublic.github.io";
  const currentPath = location.pathname;
  const fullUrl = baseUrl + currentPath;
  const locales = ["en"];

    
  const mainI18nData = {
  "default": {
    "baseSchema": {
      "organization": {
        "@type": "Organization",
        "name": "Horizon Republic",
        "url": "https://horizonrepublic.github.io"
      }
    }
  }
};
  const homePathes = locales.map(locale => locale === 'en' ? '/' : '/' + locale + '/'); ;

  const schemas = {

    

  }
  for (const homePath of homePathes) {
    schemas[homePath] = {};
  }
  
  // Get the schema for the current page
  const contentData = schemas[location.pathname];
  if (contentData) {
    let isSupportedType = true;
    const schemaType = contentData['@type'];
    const articlesWithAuthorPublisher = ['Article', 'BlogPosting', 'CollectionPage', 'Blog', 'AboutPage'];
    const servicesWithProvider = ['Service', 'WebSite'];

    if (articlesWithAuthorPublisher.includes(schemaType)) {
      contentData.author = {
        '@id': `${baseUrl}/#person`
      };
      contentData.publisher = {
        '@id': `${baseUrl}/#organization`
      };
    } else if (servicesWithProvider.includes(schemaType)) {
      contentData.provider = {
        '@id': `${baseUrl}/#organization`
      };
    } else if (schemaType === 'Organization' || schemaType === 'Person') {
      // No automatic enrichment for these types
    } else {
      isSupportedType = false;
      console.warn(`No schema.org handling for type: ${schemaType} on path: ${location.pathname}`);
    }

    if (isSupportedType) {
        contentData.url = fullUrl;
        contentData.mainEntityOfPage = {
        '@type': 'WebPage',
        '@id': `${fullUrl}#webpage`
        };
    }
  }

  // Build the full graph
  let graphData = null;
  const key = location.pathname.split('/')[1];
  let selectedPersonData = null;
  let selectedOrgData = null;
  let selectedWebsiteData = null;
  let currentLocale;
  if (locales.includes(key) && mainI18nData[key]) {
    currentLocale = key;
    // localized data
    selectedPersonData = mainI18nData[key].baseSchema ? mainI18nData[key].baseSchema.person : null;
    selectedOrgData = mainI18nData[key].baseSchema ? mainI18nData[key].baseSchema.organization : null;
    selectedWebsiteData = mainI18nData[key].baseSchema ? mainI18nData[key].baseSchema.website : null;
  }
  else {
    // default data
    selectedPersonData = mainI18nData['default'].baseSchema.person;
    selectedOrgData = mainI18nData['default'].baseSchema.organization;
    selectedWebsiteData = mainI18nData['default'].baseSchema.website;
  }

    // webpage data
    const webPageData = {
      '@type': 'WebPage',
      '@id': `${fullUrl}#webpage`,
      url: fullUrl,
      name: contentData && contentData.headline ? contentData.headline : '@horizon-republic/nestjs-jetstream',
      description: contentData && contentData.description ? contentData.description : undefined,
      inLanguage: currentLocale || 'en-US',
      isPartOf: {
        '@id': `${baseUrl}/#website`
      },
      author: contentData ? contentData.author : undefined,
      publisher: contentData ? contentData.publisher : undefined,
      provider: contentData ? contentData.provider : undefined
    };

    const graphContent = [];
    if (selectedOrgData) {
      graphContent.push(selectedOrgData);
    }
    if (selectedPersonData) {
      graphContent.push(selectedPersonData);
    }
    if (selectedWebsiteData) {
      graphContent.push(selectedWebsiteData);
    }
    graphContent.push(webPageData);

    if (contentData) {
        if (Object.keys(contentData).length > 0) {
            graphContent.push(contentData);
        }
    }
    else {
        console.warn(`No schema.org data for path: ${location.pathname}`);
    }

    graphData = {
      '@context': 'https://schema.org',
      '@graph': graphContent
    }

  return (
    <>
      {children}
      {graphData && (
        <script type='application/ld+json'>
          {JSON.stringify(graphData)}
        </script>
      )}
    </>
  );
}
  