import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/** Grouped by reader task, not by code structure. */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Start',
      collapsed: false,
      items: [
        'getting-started/why-jetstream',
        'getting-started/installation',
        'getting-started/quick-start',
        'guides/migration',
      ],
    },
    {
      type: 'category',
      label: 'Delivery patterns',
      collapsed: false,
      items: [
        'patterns/events',
        'patterns/rpc',
        'patterns/broadcast',
        'patterns/ordered-events',
        'patterns/handler-metadata',
      ],
    },
    {
      type: 'category',
      label: 'When it fails',
      collapsed: false,
      items: [
        'guides/dead-letter-queue',
        'guides/troubleshooting',
        'reference/edge-cases',
        'guides/graceful-shutdown',
        'guides/health-checks',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: false,
      items: [
        'guides/scheduling',
        'guides/per-message-ttl',
        'guides/storage-budgeting',
        'guides/stream-migration',
        'guides/multi-connection',
        'guides/external-infrastructure',
        'guides/performance',
      ],
    },
    {
      type: 'category',
      label: 'Observability',
      collapsed: false,
      link: { type: 'doc', id: 'observability/index' },
      items: ['observability/tracing', 'observability/metrics'],
    },
    {
      type: 'category',
      label: 'Extending',
      collapsed: false,
      items: [
        'guides/record-builder',
        'guides/handler-context',
        'guides/custom-codec',
        'guides/lifecycle-hooks',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'reference/module-configuration',
        'reference/default-configs',
        'reference/header-contract',
        'reference/naming-conventions',
        'reference/release-notes',
      ],
    },
    {
      type: 'category',
      label: 'API reference',
      collapsed: true,
      link: { type: 'doc', id: 'reference/api/index' },
      items: [{ type: 'autogenerated', dirName: 'reference/api' }],
    },
    {
      type: 'category',
      label: 'Project',
      collapsed: true,
      items: ['development/testing', 'development/contributing'],
    },
    {
      type: 'link',
      label: "What's new",
      href: 'https://github.com/HorizonRepublic/nestjs-jetstream/releases',
    },
  ],
};

export default sidebars;
